config/routes.rb
Restadvisor::Application.routes.draw do

  get "comments/create"
  get "comments/destroy"
resources :restos
resources :comments, only: [:create, :destroy]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :resto
end

app/models/resto.rb
class Resto < ActiveRecord::Base
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :resto_params, only: [:create]

  def create
    resto = Resto.find(params[:comment][:resto_id])
    resto.comments.create(resto_params)

    redirect_to resto
  end

  def destroy
    comment = Comment.find(params[:id])
    resto = Resto.find(comment.resto_id)
    comment.destroy

    redirect_to resto
  end

  private
  def resto_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/restos_controller.rb
class RestosController < ApplicationController

  def index
    @restos = Resto.all
  end

  def show
    @resto = Resto.find(params[:id])
  end

  def new
    @resto = Resto.new
    @resto.picture_url = "http://3.bp.blogspot.com/_ljewrW8Rm88/TNJ8KTrg9nI/AAAAAAAAEWE/HBEnCtaxzCY/s1600/restaurant+sous-marin+2.jpg"
  end

  def create
    resto = Resto.create(resto_params)
    redirect_to resto_path(resto)
  end

  def destroy
    Resto.find(params[:id]).destroy
    redirect_to restos_path
  end

  private

  def resto_params
    params.require(:resto).permit(:name, :picture_url, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/resto_helper.rb
module RestoHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Restadvisor</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/restos/index.html.erb
<h1>Bienvenue à notre sélection de restos!!</h1>

<%= link_to 'Nouveau restaurant', new_resto_path %>

<table>
  <% @restos.each do |resto|  %>
    <tr>
        <td> <%= link_to resto.name, resto_path(resto), class: "my-link" %> </td>
        <td> <%= resto.description %> </td>
        <td> <%= image_tag resto.picture_url, size: '200x100' %> </td>
    </tr>
  <% end %>
</table>

app/views/restos/new.html.erb
<h1>Veuillez créer votre restaurant</h1>

<%= form_for @resto do |f| %>
  <p> <%= f.label :name %> <%= f.text_field :name%> </p>
  <p> <%= f.label :description %> <%= f.text_area :description %> </p>
  <p> <%= f.label :picture_url %> <%= f.text_field :picture_url %> </p>
  <p> <%= f.submit "Create" %> </p>
<% end %>

<%= link_to 'Back', restos_path %>

app/views/restos/show.html.erb
<h1>Voici le restaurant selectionné</h1>

<div>
<%= image_tag @resto.picture_url, size: '200x100' %>
</div>

<p>
<%= @resto.description %>
</p>

<%= link_to "DESTROY", resto_path(@resto), method: "delete", confirm: "T'es sûr bobby?" %>

<%= link_to 'Back', restos_path %>


<p>comments
  <ul>
    <%@resto.comments.each do |comment| %>
    <li> <%= comment.body %> </li>
    <%= link_to 'supprimer', comment_path(comment), method: 'delete' %>
    <% end %>
  </ul>
</p>


<%= form_for(@resto.comments.build) do |f| %>
  <%= f.hidden_field :resto_id %>
  <%= f.label :body, "ajouter votre commentaire" %>
  <%= f.text_area :body %>
  <%= f.submit "commenter" %>
<% end %>